name: Update Publications

on:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          
      - name: Verify scripts
        run: |
          python -m py_compile .github/scripts/update_publications.py .github/scripts/update_vijay_citations.py
          
      - name: Update publications from Google Scholar
        run: |
          python .github/scripts/update_publications.py
          
      - name: Update Vijay Chauhan's publication citations from PubMed
        run: |
          python .github/scripts/update_vijay_citations.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add app/scholarship/page.tsx
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update: Publications from Google Scholar and PubMed" && git push) 